### ISSUE TITLE
Add "Disabled/Remove Notifications" under Neutron or Debloat?

### ISSUE THREAD

**Issue by Bloopy442** [SkylerWallace/ATOM#4]
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/660e39de-720c-45be-98d6-9362d4326cf8)

Settings -> Notifications -> Off

I know this is posted in the wrong section but I must be a collaborator or something to post in "Pull Requests" section.

My co-workers and I both would love this addition added, just another little simple add-on to make setups clean and simple.

Hope you don't mind me posting here, just a suggestion! Love the work, always checking back every week or so for updates.

Oh, and DropBox program added to Neutron? unless you're still keeping it GS tools approved.

Love the auto update feature in the settings, too.

**Comment by SkylerWallace** [comment]
Hey @Bloopy442 

Done
https://github.com/SkylerWallace/ATOM/commit/a2e0cc973413b27e3c427de35cc77ad7a3408541
